<?php

namespace App\Database\Migrations;

use CodeIgniter\Database\Migration;

class InsertGrupoPresupuestalData extends Migration
{
    public function up()
    {
        $data = [
            ['Nombre' => 'Mercadotecnia y publicidad', 'Descripcion' => 'Mercadotecnia y publicidad', 'activo' => true, 'ID_UnidadOperativa' => 8],
            ['Nombre' => 'Servicio celular', 'Descripcion' => 'Servicio general', 'activo' => true, 'ID_UnidadOperativa' => 8],
            ['Nombre' => 'Papeleria', 'Descripcion' => 'Papeleria', 'activo' => true, 'ID_UnidadOperativa' => 8],
            ['Nombre' => 'Dominios y hosting', 'Descripcion' => 'dominios y hosting', 'activo' => true, 'ID_UnidadOperativa' => 8],
            ['Nombre' => 'Mantto Equipo de transporte', 'Descripcion' => 'Mantto Equipo de transporte', 'activo' => true, 'ID_UnidadOperativa' => 8],
            ['Nombre' => 'Eventos ANAHUAC', 'Descripcion' => 'Eventos ANAHUAC', 'activo' => true, 'ID_UnidadOperativa' => 8],
            ['Nombre' => 'IMSS mensual', 'Descripcion' => 'IMSS', 'activo' => true, 'ID_UnidadOperativa' => 8],
            ['Nombre' => 'Infonavit', 'Descripcion' => 'infonavit', 'activo' => true, 'ID_UnidadOperativa' => 8],
            ['Nombre' => 'Impuestos sobre nomina', 'Descripcion' => 'Impuestos sobre nomina', 'activo' => true, 'ID_UnidadOperativa' => 8],
            ['Nombre' => 'CONAGUA', 'Descripcion' => 'CONAGUA', 'activo' => true, 'ID_UnidadOperativa' => 8],
            ['Nombre' => 'Pagos comisiones HSBC', 'Descripcion' => 'comision hsbc', 'activo' => true, 'ID_UnidadOperativa' => 8],
            ['Nombre' => 'Plataforma HIGO', 'Descripcion' => 'HIGO', 'activo' => true, 'ID_UnidadOperativa' => 8],
            ['Nombre' => 'Timbres icarus/otros', 'Descripcion' => 'Timbres icarus/otros', 'activo' => true, 'ID_UnidadOperativa' => 8],
            ['Nombre' => 'Renta inmobiliaria (copiadora)', 'Descripcion' => 'Timbres icarus/otros', 'activo' => true, 'ID_UnidadOperativa' => 8],
            ['Nombre' => 'Lavado de colchones', 'Descripcion' => 'Lavado de colchones', 'activo' => true, 'ID_UnidadOperativa' => 8],
            ['Nombre' => 'Capex', 'Descripcion' => 'Capex', 'activo' => true, 'ID_UnidadOperativa' => 8],
            ['Nombre' => 'Papeleria ', 'Descripcion' => 'Papeleria', 'activo' => true, 'ID_UnidadOperativa' => 6],
            ['Nombre' => 'Aditivo adblue VW', 'Descripcion' => 'Aditivo adblue VW ', 'activo' => true, 'ID_UnidadOperativa' => 3],
            ['Nombre' => 'Articulos de limpieza', 'Descripcion' => 'Articulos de limpieza', 'activo' => true, 'ID_UnidadOperativa' => 3],
            ['Nombre' => 'Consumibles de limpieza', 'Descripcion' => 'Consumibles de limpieza', 'activo' => true, 'ID_UnidadOperativa' => 3],
            ['Nombre' => 'Consumibles de motor', 'Descripcion' => 'Consumibles de motor', 'activo' => true, 'ID_UnidadOperativa' => 3],
            ['Nombre' => 'Reparaciones menores', 'Descripcion' => 'Reparaciones menores', 'activo' => true, 'ID_UnidadOperativa' => 3],
            ['Nombre' => 'Mantenimiento de unidades Vans MEC', 'Descripcion' => 'Mantenimiento de unidades Vans MEC', 'activo' => true, 'ID_UnidadOperativa' => 3],
            ['Nombre' => 'Mantenimiento de unidades Vans AA', 'Descripcion' => 'Mantenimiento de unidades Vans AA', 'activo' => true, 'ID_UnidadOperativa' => 3],
            ['Nombre' => 'Mantenimiento de unidades Bus MEC', 'Descripcion' => 'Mantenimiento de unidades Bus MEC', 'activo' => true, 'ID_UnidadOperativa' => 3],
            ['Nombre' => 'OTAS 21%', 'Descripcion' => 'OTAS 21%', 'activo' => true, 'ID_UnidadOperativa' => 2],
            ['Nombre' => 'Insumos de limpieza', 'Descripcion' => 'Insumos de limpieza', 'activo' => true, 'ID_UnidadOperativa' => 2],
            ['Nombre' => 'Insumos de mantenimiento', 'Descripcion' => 'Insumos de mantenimiento', 'activo' => true, 'ID_UnidadOperativa' => 2],
            ['Nombre' => 'Papeleria', 'Descripcion' => 'Papeleria', 'activo' => true, 'ID_UnidadOperativa' => 2],
            ['Nombre' => 'Renta de inmobiliario y equipo (OTV)', 'Descripcion' => 'Renta de inmobiliario y equipo (OTV)', 'activo' => true, 'ID_UnidadOperativa' => 2],
            ['Nombre' => 'CFE', 'Descripcion' => 'CFE', 'activo' => true, 'ID_UnidadOperativa' => 2],
            ['Nombre' => 'Lavanderia', 'Descripcion' => 'Lavanderia', 'activo' => true, 'ID_UnidadOperativa' => 2],
            ['Nombre' => 'Amenidades ', 'Descripcion' => 'Agua, detalles', 'activo' => true, 'ID_UnidadOperativa' => 2],
            ['Nombre' => 'Kone', 'Descripcion' => 'Kone', 'activo' => true, 'ID_UnidadOperativa' => 2],
            ['Nombre' => 'Fumigacion', 'Descripcion' => 'Fumigacion', 'activo' => true, 'ID_UnidadOperativa' => 2],
            ['Nombre' => 'Lavado de Alfombras/muebles', 'Descripcion' => 'Lavado de Alfombras/muebles', 'activo' => true, 'ID_UnidadOperativa' => 2],
            ['Nombre' => 'Pintura de pasillos, cuartos y lobby', 'Descripcion' => 'Pintura', 'activo' => true, 'ID_UnidadOperativa' => 2],
            ['Nombre' => 'Impermeabilizante', 'Descripcion' => 'Impermeabilizante', 'activo' => true, 'ID_UnidadOperativa' => 2],
            ['Nombre' => 'Trabajo en Boilers', 'Descripcion' => 'Trabajo en Boilers', 'activo' => true, 'ID_UnidadOperativa' => 2],
            ['Nombre' => 'Dispensador de amenidades', 'Descripcion' => 'dispensador', 'activo' => true, 'ID_UnidadOperativa' => 2],
            ['Nombre' => 'Trabajos de tablaroca', 'Descripcion' => 'tablaroca', 'activo' => true, 'ID_UnidadOperativa' => 2],
            ['Nombre' => 'Cambio de mobiliario', 'Descripcion' => 'Cambio de mobiliario', 'activo' => true, 'ID_UnidadOperativa' => 2],
            ['Nombre' => 'Mantenimiento de unidades Bus AA', 'Descripcion' => 'Mantenimiento de unidades Bus AA', 'activo' => true, 'ID_UnidadOperativa' => 3],
            ['Nombre' => 'gasolina', 'Descripcion' => 'gas ', 'activo' => true, 'ID_UnidadOperativa' => 3],
            ['Nombre' => 'IMSS', 'Descripcion' => 'IMSS', 'activo' => true, 'ID_UnidadOperativa' => 3],
            ['Nombre' => 'Telefonia', 'Descripcion' => 'Telefonia', 'activo' => true, 'ID_UnidadOperativa' => 3],
            ['Nombre' => 'Leasing bus', 'Descripcion' => 'Leasing bus', 'activo' => true, 'ID_UnidadOperativa' => 3],
            ['Nombre' => 'Leasing Van', 'Descripcion' => 'Leasing Van', 'activo' => true, 'ID_UnidadOperativa' => 3],
            ['Nombre' => 'Contingencias', 'Descripcion' => 'Contingencias', 'activo' => true, 'ID_UnidadOperativa' => 3],
            ['Nombre' => 'Seguros', 'Descripcion' => 'Seguritos', 'activo' => true, 'ID_UnidadOperativa' => 3],
            ['Nombre' => 'Papeleria', 'Descripcion' => 'Papeleria', 'activo' => true, 'ID_UnidadOperativa' => 4],
            ['Nombre' => 'Insumos de palomitas', 'Descripcion' => 'Palomitas', 'activo' => true, 'ID_UnidadOperativa' => 4],
            ['Nombre' => 'Materiales áreas comunes', 'Descripcion' => 'Materiales áreas comunes', 'activo' => true, 'ID_UnidadOperativa' => 4],
            ['Nombre' => 'Bikini Buttom Party', 'Descripcion' => 'Bikini Buttom Party', 'activo' => true, 'ID_UnidadOperativa' => 4],
            ['Nombre' => 'Pausa Bonita (Febrero)', 'Descripcion' => 'Pausa Bonita (Febrero)', 'activo' => true, 'ID_UnidadOperativa' => 4],
            ['Nombre' => 'Kore And Rive (Febrero)', 'Descripcion' => 'Kore And Rive (Febrero)', 'activo' => true, 'ID_UnidadOperativa' => 4],
            ['Nombre' => 'Olimpiadas (Febrero)', 'Descripcion' => 'Olimpiadas (Febrero)', 'activo' => true, 'ID_UnidadOperativa' => 4],
            ['Nombre' => 'Movie Night (abril)', 'Descripcion' => 'Movie Night (abril)', 'activo' => true, 'ID_UnidadOperativa' => 4],
            ['Nombre' => 'Last Bloom (abril)', 'Descripcion' => 'Last Bloom (abril)', 'activo' => true, 'ID_UnidadOperativa' => 4],
            ['Nombre' => 'THRIFTSHOP (Abril)', 'Descripcion' => 'THRIFTSHOP (Abril)', 'activo' => true, 'ID_UnidadOperativa' => 4],
            ['Nombre' => 'Drink And Draw (mayo)', 'Descripcion' => 'Drink And Draw (mayo)', 'activo' => true, 'ID_UnidadOperativa' => 4],
            ['Nombre' => 'Breakfast Movie (Mayo)', 'Descripcion' => 'Breakfast Movie (Mayo)', 'activo' => true, 'ID_UnidadOperativa' => 4],
            ['Nombre' => 'Game Over (Mayo)', 'Descripcion' => 'Game Over (Mayo)', 'activo' => true, 'ID_UnidadOperativa' => 4],
            ['Nombre' => 'Pool Party', 'Descripcion' => 'Pool Partu', 'activo' => true, 'ID_UnidadOperativa' => 4],
            ['Nombre' => 'Halloween party', 'Descripcion' => 'Halloween party', 'activo' => true, 'ID_UnidadOperativa' => 4],
            ['Nombre' => 'THRIFTSHOP ', 'Descripcion' => 'THRIFTSHOP ', 'activo' => true, 'ID_UnidadOperativa' => 4],
            ['Nombre' => 'Papeleria', 'Descripcion' => 'Papeleria', 'activo' => true, 'ID_UnidadOperativa' => 5],
            ['Nombre' => 'Papeleria', 'Descripcion' => 'Papeleria', 'activo' => true, 'ID_UnidadOperativa' => 7],
            ['Nombre' => 'Consumibles del depto', 'Descripcion' => 'Consumibles del depto', 'activo' => true, 'ID_UnidadOperativa' => 5],
            ['Nombre' => 'Consumibles para el area Grill, games R. y salon de estudios', 'Descripcion' => 'Consumibles para el area Grill, games R. y salon de estudios', 'activo' => true, 'ID_UnidadOperativa' => 5],
            ['Nombre' => 'Consomubles Gimancio', 'Descripcion' => 'Gimnacio', 'activo' => true, 'ID_UnidadOperativa' => 5],
            ['Nombre' => 'Consumibles Piscina', 'Descripcion' => 'Consumibles Piscina', 'activo' => true, 'ID_UnidadOperativa' => 5],
            ['Nombre' => 'Consumibles áreas con pasillos', 'Descripcion' => 'Consumibles áreas con pasillos', 'activo' => true, 'ID_UnidadOperativa' => 5],
            ['Nombre' => 'Consumibles Jardineria', 'Descripcion' => 'Consumibles Jardineria', 'activo' => true, 'ID_UnidadOperativa' => 5],
            ['Nombre' => 'Fumigación', 'Descripcion' => 'Fumigación', 'activo' => true, 'ID_UnidadOperativa' => 5],
            ['Nombre' => 'Gas LP Edf. 7,8 y 9', 'Descripcion' => 'Gas LP Edf. 7,8 y 9', 'activo' => true, 'ID_UnidadOperativa' => 5],
            ['Nombre' => 'Herramientas y Mantto general de motores Complejo', 'Descripcion' => 'Herramientas y Mantto general de motores Complejo', 'activo' => true, 'ID_UnidadOperativa' => 5],
            ['Nombre' => 'Laboratorio de Petar', 'Descripcion' => 'Lasb', 'activo' => true, 'ID_UnidadOperativa' => 5],
            ['Nombre' => 'Quimicos', 'Descripcion' => 'Quimicos ', 'activo' => true, 'ID_UnidadOperativa' => 5],
            ['Nombre' => 'Insumos', 'Descripcion' => 'Insumos', 'activo' => true, 'ID_UnidadOperativa' => 5],
            ['Nombre' => 'Telmex Servicios (6)', 'Descripcion' => 'Telmex Servicios (6)', 'activo' => true, 'ID_UnidadOperativa' => 6],
            ['Nombre' => 'Hosting y Dominios', 'Descripcion' => 'Hosting y dom', 'activo' => true, 'ID_UnidadOperativa' => 6],
            ['Nombre' => 'Router / AP', 'Descripcion' => 'Router / AP', 'activo' => true, 'ID_UnidadOperativa' => 6],
            ['Nombre' => 'Cerraduras electricas', 'Descripcion' => 'Cerraduras', 'activo' => true, 'ID_UnidadOperativa' => 6],
            ['Nombre' => 'Tel ip/ analog', 'Descripcion' => 'Tel ip/ analog', 'activo' => true, 'ID_UnidadOperativa' => 6],
            ['Nombre' => 'Bobina UTP', 'Descripcion' => 'Bobina UTP', 'activo' => true, 'ID_UnidadOperativa' => 6],
            ['Nombre' => 'Herramienta/Accesorios', 'Descripcion' => 'Herramienta/Accesorios', 'activo' => true, 'ID_UnidadOperativa' => 6],
            ['Nombre' => 'Baterias AA (Cerraduras)', 'Descripcion' => 'Baterias AA (Cerraduras)', 'activo' => true, 'ID_UnidadOperativa' => 6],
            ['Nombre' => 'Tarjetas RFID (Cerraduras)', 'Descripcion' => 'Tarjetas RFID (Cerraduras)', 'activo' => true, 'ID_UnidadOperativa' => 6],
            ['Nombre' => 'Manos Libres Para Radio', 'Descripcion' => 'Manos Libres Para Radio', 'activo' => true, 'ID_UnidadOperativa' => 7],
            ['Nombre' => 'Pila para radio comunicador', 'Descripcion' => 'Pila para radio comunicador', 'activo' => true, 'ID_UnidadOperativa' => 7],
            ['Nombre' => 'Radiocomunicador', 'Descripcion' => 'Radio', 'activo' => true, 'ID_UnidadOperativa' => 7],
            ['Nombre' => 'Lamparas Recargables', 'Descripcion' => 'Lamparas', 'activo' => true, 'ID_UnidadOperativa' => 7],
            ['Nombre' => 'Viaticos', 'Descripcion' => 'Viaticos', 'activo' => true, 'ID_UnidadOperativa' => 8],
            ['Nombre' => 'Convivios y eventos Vtas', 'Descripcion' => 'Convivios y eventos Vtas', 'activo' => true, 'ID_UnidadOperativa' => 8],
            ['Nombre' => 'obsequios', 'Descripcion' => 'obsequios', 'activo' => true, 'ID_UnidadOperativa' => 8],
            ['Nombre' => 'Combustible', 'Descripcion' => 'Combustible', 'activo' => true, 'ID_UnidadOperativa' => 8],
            ['Nombre' => 'CRM y aplicaciones', 'Descripcion' => 'CRM y aplicaciones', 'activo' => true, 'ID_UnidadOperativa' => 8],
            ['Nombre' => 'Souvenir', 'Descripcion' => 'Souvenir', 'activo' => true, 'ID_UnidadOperativa' => 8],
            ['Nombre' => 'Retiro Cesantia y vejez', 'Descripcion' => 'Retiro Cesantia y vejez', 'activo' => true, 'ID_UnidadOperativa' => 8],
            ['Nombre' => 'Creditos infonavit', 'Descripcion' => 'Creditos infonavit', 'activo' => true, 'ID_UnidadOperativa' => 8],
            ['Nombre' => 'CFE', 'Descripcion' => 'CFE', 'activo' => true, 'ID_UnidadOperativa' => 8],
            ['Nombre' => 'Agua empleados', 'Descripcion' => 'agua', 'activo' => true, 'ID_UnidadOperativa' => 8],
            ['Nombre' => 'Software campus icarus y contpaq', 'Descripcion' => 'Software campus icarus y contpaq', 'activo' => true, 'ID_UnidadOperativa' => 8],
            ['Nombre' => 'Uniformes', 'Descripcion' => 'uniformes', 'activo' => true, 'ID_UnidadOperativa' => 8],
            ['Nombre' => 'Asesoramiento Cumplimiento PLD', 'Descripcion' => 'Asesoramiento PLD', 'activo' => true, 'ID_UnidadOperativa' => 8],
            ['Nombre' => 'Paneles solares', 'Descripcion' => 'Paneles solares', 'activo' => true, 'ID_UnidadOperativa' => 8],
            ['Nombre' => 'seguro propiedad', 'Descripcion' => 'seguro propiedad', 'activo' => true, 'ID_UnidadOperativa' => 8],
            ['Nombre' => 'Gastos sistemas', 'Descripcion' => 'gastos', 'activo' => true, 'ID_UnidadOperativa' => 9],
        ];

        $this->db->table('GrupoPresupuestal')->insertBatch($data);
    }

    public function down()
    {
        // Como los IDs se generan dinámicamente, hacemos rollback eliminando por los nombres
        // de los registros que insertamos originalmente.
        $nombresInsertados = [
            'Mercadotecnia y publicidad', 'Servicio celular', 'Papeleria', 'Dominios y hosting',
            'Mantto Equipo de transporte', 'Eventos ANAHUAC', 'IMSS mensual', 'Infonavit',
            'Impuestos sobre nomina', 'CONAGUA', 'Pagos comisiones HSBC', 'Plataforma HIGO',
            'Timbres icarus/otros', 'Renta inmobiliaria (copiadora)', 'Lavado de colchones', 'Capex',
            'Papeleria ', 'Aditivo adblue VW', 'Articulos de limpieza', 'Consumibles de limpieza',
            'Consumibles de motor', 'Reparaciones menores', 'Mantenimiento de unidades Vans MEC',
            'Mantenimiento de unidades Vans AA', 'Mantenimiento de unidades Bus MEC', 'OTAS 21%',
            'Insumos de limpieza', 'Insumos de mantenimiento', 'Renta de inmobiliario y equipo (OTV)',
            'CFE', 'Lavanderia', 'Amenidades ', 'Kone', 'Fumigacion', 'Lavado de Alfombras/muebles',
            'Pintura de pasillos, cuartos y lobby', 'Impermeabilizante', 'Trabajo en Boilers',
            'Dispensador de amenidades', 'Trabajos de tablaroca', 'Cambio de mobiliario',
            'Mantenimiento de unidades Bus AA', 'gasolina', 'IMSS', 'Telefonia', 'Leasing bus',
            'Leasing Van', 'Contingencias', 'Seguros', 'Insumos de palomitas', 'Materiales áreas comunes',
            'Bikini Buttom Party', 'Pausa Bonita (Febrero)', 'Kore And Rive (Febrero)', 'Olimpiadas (Febrero)',
            'Movie Night (abril)', 'Last Bloom (abril)', 'THRIFTSHOP (Abril)', 'Drink And Draw (mayo)',
            'Breakfast Movie (Mayo)', 'Game Over (Mayo)', 'Pool Party', 'Halloween party', 'THRIFTSHOP ',
            'Consumibles del depto', 'Consumibles para el area Grill, games R. y salon de estudios',
            'Consomubles Gimancio', 'Consumibles Piscina', 'Consumibles áreas con pasillos',
            'Consumibles Jardineria', 'Fumigación', 'Gas LP Edf. 7,8 y 9',
            'Herramientas y Mantto general de motores Complejo', 'Laboratorio de Petar', 'Quimicos',
            'Insumos', 'Telmex Servicios (6)', 'Hosting y Dominios', 'Router / AP', 'Cerraduras electricas',
            'Tel ip/ analog', 'Bobina UTP', 'Herramienta/Accesorios', 'Baterias AA (Cerraduras)',
            'Tarjetas RFID (Cerraduras)', 'Manos Libres Para Radio', 'Pila para radio comunicador',
            'Radiocomunicador', 'Lamparas Recargables', 'Viaticos', 'Convivios y eventos Vtas', 'obsequios',
            'Combustible', 'CRM y aplicaciones', 'Souvenir', 'Retiro Cesantia y vejez', 'Creditos infonavit',
            'Agua empleados', 'Software campus icarus y contpaq', 'Uniformes', 'Asesoramiento Cumplimiento PLD',
            'Paneles solares', 'seguro propiedad', 'Gastos sistemas'
        ];

        $this->db->table('GrupoPresupuestal')->whereIn('Nombre', $nombresInsertados)->delete();
    }
}