<?php

namespace App\Database\Migrations;

use CodeIgniter\Database\Migration;

class InsertGrupoPresupuestalData extends Migration
{
    public function up()
    {
        $data = [
            ['ID_GrupoPresupuestal' => 78, 'Nombre' => 'Mercadotecnia y publicidad', 'Descripcion' => 'Mercadotecnia y publicidad', 'activo' => true, 'ID_UnidadOperativa' => 8],
            ['ID_GrupoPresupuestal' => 80, 'Nombre' => 'Servicio celular', 'Descripcion' => 'Servicio general', 'activo' => true, 'ID_UnidadOperativa' => 8],
            ['ID_GrupoPresupuestal' => 82, 'Nombre' => 'Papeleria', 'Descripcion' => 'Papeleria', 'activo' => true, 'ID_UnidadOperativa' => 8],
            ['ID_GrupoPresupuestal' => 84, 'Nombre' => 'Dominios y hosting', 'Descripcion' => 'dominios y hosting', 'activo' => true, 'ID_UnidadOperativa' => 8],
            ['ID_GrupoPresupuestal' => 86, 'Nombre' => 'Mantto Equipo de transporte', 'Descripcion' => 'Mantto Equipo de transporte', 'activo' => true, 'ID_UnidadOperativa' => 8],
            ['ID_GrupoPresupuestal' => 88, 'Nombre' => 'Eventos ANAHUAC', 'Descripcion' => 'Eventos ANAHUAC', 'activo' => true, 'ID_UnidadOperativa' => 8],
            ['ID_GrupoPresupuestal' => 90, 'Nombre' => 'IMSS mensual', 'Descripcion' => 'IMSS', 'activo' => true, 'ID_UnidadOperativa' => 8],
            ['ID_GrupoPresupuestal' => 92, 'Nombre' => 'Infonavit', 'Descripcion' => 'infonavit', 'activo' => true, 'ID_UnidadOperativa' => 8],
            ['ID_GrupoPresupuestal' => 94, 'Nombre' => 'Impuestos sobre nomina', 'Descripcion' => 'Impuestos sobre nomina', 'activo' => true, 'ID_UnidadOperativa' => 8],
            ['ID_GrupoPresupuestal' => 96, 'Nombre' => 'CONAGUA', 'Descripcion' => 'CONAGUA', 'activo' => true, 'ID_UnidadOperativa' => 8],
            ['ID_GrupoPresupuestal' => 98, 'Nombre' => 'Pagos comisiones HSBC', 'Descripcion' => 'comision hsbc', 'activo' => true, 'ID_UnidadOperativa' => 8],
            ['ID_GrupoPresupuestal' => 100, 'Nombre' => 'Plataforma HIGO', 'Descripcion' => 'HIGO', 'activo' => true, 'ID_UnidadOperativa' => 8],
            ['ID_GrupoPresupuestal' => 102, 'Nombre' => 'Timbres icarus/otros', 'Descripcion' => 'Timbres icarus/otros', 'activo' => true, 'ID_UnidadOperativa' => 8],
            ['ID_GrupoPresupuestal' => 104, 'Nombre' => 'Renta inmobiliaria (copiadora)', 'Descripcion' => 'Timbres icarus/otros', 'activo' => true, 'ID_UnidadOperativa' => 8],
            ['ID_GrupoPresupuestal' => 106, 'Nombre' => 'Lavado de colchones', 'Descripcion' => 'Lavado de colchones', 'activo' => true, 'ID_UnidadOperativa' => 8],
            ['ID_GrupoPresupuestal' => 108, 'Nombre' => 'Capex', 'Descripcion' => 'Capex', 'activo' => true, 'ID_UnidadOperativa' => 8],
            ['ID_GrupoPresupuestal' => 110, 'Nombre' => 'Papeleria ', 'Descripcion' => 'Papeleria', 'activo' => true, 'ID_UnidadOperativa' => 6],
            ['ID_GrupoPresupuestal' => 62, 'Nombre' => 'Aditivo adblue VW', 'Descripcion' => 'Aditivo adblue VW ', 'activo' => true, 'ID_UnidadOperativa' => 3],
            ['ID_GrupoPresupuestal' => 63, 'Nombre' => 'Articulos de limpieza', 'Descripcion' => 'Articulos de limpieza', 'activo' => true, 'ID_UnidadOperativa' => 3],
            ['ID_GrupoPresupuestal' => 64, 'Nombre' => 'Consumibles de limpieza', 'Descripcion' => 'Consumibles de limpieza', 'activo' => true, 'ID_UnidadOperativa' => 3],
            ['ID_GrupoPresupuestal' => 65, 'Nombre' => 'Consumibles de motor', 'Descripcion' => 'Consumibles de motor', 'activo' => true, 'ID_UnidadOperativa' => 3],
            ['ID_GrupoPresupuestal' => 66, 'Nombre' => 'Reparaciones menores', 'Descripcion' => 'Reparaciones menores', 'activo' => true, 'ID_UnidadOperativa' => 3],
            ['ID_GrupoPresupuestal' => 67, 'Nombre' => 'Mantenimiento de unidades Vans MEC', 'Descripcion' => 'Mantenimiento de unidades Vans MEC', 'activo' => true, 'ID_UnidadOperativa' => 3],
            ['ID_GrupoPresupuestal' => 68, 'Nombre' => 'Mantenimiento de unidades Vans AA', 'Descripcion' => 'Mantenimiento de unidades Vans AA', 'activo' => true, 'ID_UnidadOperativa' => 3],
            ['ID_GrupoPresupuestal' => 69, 'Nombre' => 'Mantenimiento de unidades Bus MEC', 'Descripcion' => 'Mantenimiento de unidades Bus MEC', 'activo' => true, 'ID_UnidadOperativa' => 3],
            ['ID_GrupoPresupuestal' => 45, 'Nombre' => 'OTAS 21%', 'Descripcion' => 'OTAS 21%', 'activo' => true, 'ID_UnidadOperativa' => 2],
            ['ID_GrupoPresupuestal' => 46, 'Nombre' => 'Insumos de limpieza', 'Descripcion' => 'Insumos de limpieza', 'activo' => true, 'ID_UnidadOperativa' => 2],
            ['ID_GrupoPresupuestal' => 47, 'Nombre' => 'Insumos de mantenimiento', 'Descripcion' => 'Insumos de mantenimiento', 'activo' => true, 'ID_UnidadOperativa' => 2],
            ['ID_GrupoPresupuestal' => 48, 'Nombre' => 'Papeleria', 'Descripcion' => 'Papeleria', 'activo' => true, 'ID_UnidadOperativa' => 2],
            ['ID_GrupoPresupuestal' => 49, 'Nombre' => 'Renta de inmobiliario y equipo (OTV)', 'Descripcion' => 'Renta de inmobiliario y equipo (OTV)', 'activo' => true, 'ID_UnidadOperativa' => 2],
            ['ID_GrupoPresupuestal' => 50, 'Nombre' => 'CFE', 'Descripcion' => 'CFE', 'activo' => true, 'ID_UnidadOperativa' => 2],
            ['ID_GrupoPresupuestal' => 51, 'Nombre' => 'Lavanderia', 'Descripcion' => 'Lavanderia', 'activo' => true, 'ID_UnidadOperativa' => 2],
            ['ID_GrupoPresupuestal' => 52, 'Nombre' => 'Amenidades ', 'Descripcion' => 'Agua, detalles', 'activo' => true, 'ID_UnidadOperativa' => 2],
            ['ID_GrupoPresupuestal' => 53, 'Nombre' => 'Kone', 'Descripcion' => 'Kone', 'activo' => true, 'ID_UnidadOperativa' => 2],
            ['ID_GrupoPresupuestal' => 54, 'Nombre' => 'Fumigacion', 'Descripcion' => 'Fumigacion', 'activo' => true, 'ID_UnidadOperativa' => 2],
            ['ID_GrupoPresupuestal' => 55, 'Nombre' => 'Lavado de Alfombras/muebles', 'Descripcion' => 'Lavado de Alfombras/muebles', 'activo' => true, 'ID_UnidadOperativa' => 2],
            ['ID_GrupoPresupuestal' => 56, 'Nombre' => 'Pintura de pasillos, cuartos y lobby', 'Descripcion' => 'Pintura', 'activo' => true, 'ID_UnidadOperativa' => 2],
            ['ID_GrupoPresupuestal' => 57, 'Nombre' => 'Impermeabilizante', 'Descripcion' => 'Impermeabilizante', 'activo' => true, 'ID_UnidadOperativa' => 2],
            ['ID_GrupoPresupuestal' => 58, 'Nombre' => 'Trabajo en Boilers', 'Descripcion' => 'Trabajo en Boilers', 'activo' => true, 'ID_UnidadOperativa' => 2],
            ['ID_GrupoPresupuestal' => 59, 'Nombre' => 'Dispensador de amenidades', 'Descripcion' => 'dispensador', 'activo' => true, 'ID_UnidadOperativa' => 2],
            ['ID_GrupoPresupuestal' => 60, 'Nombre' => 'Trabajos de tablaroca', 'Descripcion' => 'tablaroca', 'activo' => true, 'ID_UnidadOperativa' => 2],
            ['ID_GrupoPresupuestal' => 61, 'Nombre' => 'Cambio de mobiliario', 'Descripcion' => 'Cambio de mobiliario', 'activo' => true, 'ID_UnidadOperativa' => 2],
            ['ID_GrupoPresupuestal' => 70, 'Nombre' => 'Mantenimiento de unidades Bus AA', 'Descripcion' => 'Mantenimiento de unidades Bus AA', 'activo' => true, 'ID_UnidadOperativa' => 3],
            ['ID_GrupoPresupuestal' => 71, 'Nombre' => 'gasolina', 'Descripcion' => 'gas ', 'activo' => true, 'ID_UnidadOperativa' => 3],
            ['ID_GrupoPresupuestal' => 72, 'Nombre' => 'IMSS', 'Descripcion' => 'IMSS', 'activo' => true, 'ID_UnidadOperativa' => 3],
            ['ID_GrupoPresupuestal' => 74, 'Nombre' => 'Telefonia', 'Descripcion' => 'Telefonia', 'activo' => true, 'ID_UnidadOperativa' => 3],
            ['ID_GrupoPresupuestal' => 75, 'Nombre' => 'Leasing bus', 'Descripcion' => 'Leasing bus', 'activo' => true, 'ID_UnidadOperativa' => 3],
            ['ID_GrupoPresupuestal' => 76, 'Nombre' => 'Leasing Van', 'Descripcion' => 'Leasing Van', 'activo' => true, 'ID_UnidadOperativa' => 3],
            ['ID_GrupoPresupuestal' => 77, 'Nombre' => 'Contingencias', 'Descripcion' => 'Contingencias', 'activo' => true, 'ID_UnidadOperativa' => 3],
            ['ID_GrupoPresupuestal' => 73, 'Nombre' => 'Seguros', 'Descripcion' => 'Seguritos', 'activo' => true, 'ID_UnidadOperativa' => 3],
            ['ID_GrupoPresupuestal' => 2, 'Nombre' => 'Papeleria', 'Descripcion' => 'Papeleria', 'activo' => true, 'ID_UnidadOperativa' => 5],
            ['ID_GrupoPresupuestal' => 3, 'Nombre' => 'Insumos de palomitas', 'Descripcion' => 'Palomitas', 'activo' => true, 'ID_UnidadOperativa' => 4],
            ['ID_GrupoPresupuestal' => 4, 'Nombre' => 'Materiales áreas comunes', 'Descripcion' => 'Materiales áreas comunes', 'activo' => true, 'ID_UnidadOperativa' => 4],
            ['ID_GrupoPresupuestal' => 5, 'Nombre' => 'Bikini Buttom Party', 'Descripcion' => 'Bikini Buttom Party', 'activo' => true, 'ID_UnidadOperativa' => 4],
            ['ID_GrupoPresupuestal' => 6, 'Nombre' => 'Pausa Bonita (Febrero)', 'Descripcion' => 'Pausa Bonita (Febrero)', 'activo' => true, 'ID_UnidadOperativa' => 4],
            ['ID_GrupoPresupuestal' => 7, 'Nombre' => 'Kore And Rive (Febrero)', 'Descripcion' => 'Kore And Rive (Febrero)', 'activo' => true, 'ID_UnidadOperativa' => 4],
            ['ID_GrupoPresupuestal' => 8, 'Nombre' => 'Olimpiadas (Febrero)', 'Descripcion' => 'Olimpiadas (Febrero)', 'activo' => true, 'ID_UnidadOperativa' => 4],
            ['ID_GrupoPresupuestal' => 9, 'Nombre' => 'Movie Night (abril)', 'Descripcion' => 'Movie Night (abril)', 'activo' => true, 'ID_UnidadOperativa' => 4],
            ['ID_GrupoPresupuestal' => 10, 'Nombre' => 'Last Bloom (abril)', 'Descripcion' => 'Last Bloom (abril)', 'activo' => true, 'ID_UnidadOperativa' => 4],
            ['ID_GrupoPresupuestal' => 11, 'Nombre' => 'THRIFTSHOP (Abril)', 'Descripcion' => 'THRIFTSHOP (Abril)', 'activo' => true, 'ID_UnidadOperativa' => 4],
            ['ID_GrupoPresupuestal' => 12, 'Nombre' => 'Breakfast Movie (Mayo)', 'Descripcion' => 'Breakfast Movie (Mayo)', 'activo' => true, 'ID_UnidadOperativa' => 4],
            ['ID_GrupoPresupuestal' => 13, 'Nombre' => 'Drink And Draw (mayo)', 'Descripcion' => 'Drink And Draw (mayo)', 'activo' => true, 'ID_UnidadOperativa' => 4],
            ['ID_GrupoPresupuestal' => 14, 'Nombre' => 'Game Over (Mayo)', 'Descripcion' => 'Game Over (Mayo)', 'activo' => true, 'ID_UnidadOperativa' => 4],
            ['ID_GrupoPresupuestal' => 15, 'Nombre' => 'Pool Party', 'Descripcion' => 'Pool Partu', 'activo' => true, 'ID_UnidadOperativa' => 4],
            ['ID_GrupoPresupuestal' => 16, 'Nombre' => 'Halloween party', 'Descripcion' => 'Halloween party', 'activo' => true, 'ID_UnidadOperativa' => 4],
            ['ID_GrupoPresupuestal' => 17, 'Nombre' => 'THRIFTSHOP ', 'Descripcion' => 'THRIFTSHOP ', 'activo' => true, 'ID_UnidadOperativa' => 4],
            ['ID_GrupoPresupuestal' => 18, 'Nombre' => 'Consumibles del depto', 'Descripcion' => 'Consumibles del depto', 'activo' => true, 'ID_UnidadOperativa' => 5],
            ['ID_GrupoPresupuestal' => 19, 'Nombre' => 'Consumibles para el area Grill, games R. y salon de estudios', 'Descripcion' => 'Consumibles para el area Grill, games R. y salon de estudios', 'activo' => true, 'ID_UnidadOperativa' => 5],
            ['ID_GrupoPresupuestal' => 20, 'Nombre' => 'Consomubles Gimancio', 'Descripcion' => 'Gimnacio', 'activo' => true, 'ID_UnidadOperativa' => 5],
            ['ID_GrupoPresupuestal' => 21, 'Nombre' => 'Consumibles Piscina', 'Descripcion' => 'Consumibles Piscina', 'activo' => true, 'ID_UnidadOperativa' => 5],
            ['ID_GrupoPresupuestal' => 22, 'Nombre' => 'Consumibles áreas con pasillos', 'Descripcion' => 'Consumibles áreas con pasillos', 'activo' => true, 'ID_UnidadOperativa' => 5],
            ['ID_GrupoPresupuestal' => 23, 'Nombre' => 'Consumibles Jardineria', 'Descripcion' => 'Consumibles Jardineria', 'activo' => true, 'ID_UnidadOperativa' => 5],
            ['ID_GrupoPresupuestal' => 24, 'Nombre' => 'Fumigación', 'Descripcion' => 'Fumigación', 'activo' => true, 'ID_UnidadOperativa' => 5],
            ['ID_GrupoPresupuestal' => 25, 'Nombre' => 'Gas LP Edf. 7,8 y 9', 'Descripcion' => 'Gas LP Edf. 7,8 y 9', 'activo' => true, 'ID_UnidadOperativa' => 5],
            ['ID_GrupoPresupuestal' => 26, 'Nombre' => 'Herramientas y Mantto general de motores Complejo', 'Descripcion' => 'Herramientas y Mantto general de motores Complejo', 'activo' => true, 'ID_UnidadOperativa' => 5],
            ['ID_GrupoPresupuestal' => 27, 'Nombre' => 'Laboratorio de Petar', 'Descripcion' => 'Lasb', 'activo' => true, 'ID_UnidadOperativa' => 5],
            ['ID_GrupoPresupuestal' => 28, 'Nombre' => 'Papeleria', 'Descripcion' => 'Papeleria', 'activo' => true, 'ID_UnidadOperativa' => 4],
            ['ID_GrupoPresupuestal' => 29, 'Nombre' => 'Quimicos', 'Descripcion' => 'Quimicos ', 'activo' => true, 'ID_UnidadOperativa' => 5],
            ['ID_GrupoPresupuestal' => 30, 'Nombre' => 'Insumos', 'Descripcion' => 'Insumos', 'activo' => true, 'ID_UnidadOperativa' => 5],
            ['ID_GrupoPresupuestal' => 31, 'Nombre' => 'Telmex Servicios (6)', 'Descripcion' => 'Telmex Servicios (6)', 'activo' => true, 'ID_UnidadOperativa' => 6],
            ['ID_GrupoPresupuestal' => 32, 'Nombre' => 'Hosting y Dominios', 'Descripcion' => 'Hosting y dom', 'activo' => true, 'ID_UnidadOperativa' => 6],
            ['ID_GrupoPresupuestal' => 33, 'Nombre' => 'Router / AP', 'Descripcion' => 'Router / AP', 'activo' => true, 'ID_UnidadOperativa' => 6],
            ['ID_GrupoPresupuestal' => 34, 'Nombre' => 'Cerraduras electricas', 'Descripcion' => 'Cerraduras', 'activo' => true, 'ID_UnidadOperativa' => 6],
            ['ID_GrupoPresupuestal' => 35, 'Nombre' => 'Tel ip/ analog', 'Descripcion' => 'Tel ip/ analog', 'activo' => true, 'ID_UnidadOperativa' => 6],
            ['ID_GrupoPresupuestal' => 36, 'Nombre' => 'Bobina UTP', 'Descripcion' => 'Bobina UTP', 'activo' => true, 'ID_UnidadOperativa' => 6],
            ['ID_GrupoPresupuestal' => 37, 'Nombre' => 'Herramienta/Accesorios', 'Descripcion' => 'Herramienta/Accesorios', 'activo' => true, 'ID_UnidadOperativa' => 6],
            ['ID_GrupoPresupuestal' => 38, 'Nombre' => 'Baterias AA (Cerraduras)', 'Descripcion' => 'Baterias AA (Cerraduras)', 'activo' => true, 'ID_UnidadOperativa' => 6],
            ['ID_GrupoPresupuestal' => 39, 'Nombre' => 'Tarjetas RFID (Cerraduras)', 'Descripcion' => 'Tarjetas RFID (Cerraduras)', 'activo' => true, 'ID_UnidadOperativa' => 6],
            ['ID_GrupoPresupuestal' => 40, 'Nombre' => 'Papeleria', 'Descripcion' => 'Papeleria', 'activo' => true, 'ID_UnidadOperativa' => 7],
            ['ID_GrupoPresupuestal' => 41, 'Nombre' => 'Radiocomunicador', 'Descripcion' => 'Radio', 'activo' => true, 'ID_UnidadOperativa' => 7],
            ['ID_GrupoPresupuestal' => 42, 'Nombre' => 'Pila para radio comunicador', 'Descripcion' => 'Pila para radio comunicador', 'activo' => true, 'ID_UnidadOperativa' => 7],
            ['ID_GrupoPresupuestal' => 43, 'Nombre' => 'Manos Libres Para Radio', 'Descripcion' => 'Manos Libres Para Radio', 'activo' => true, 'ID_UnidadOperativa' => 7],
            ['ID_GrupoPresupuestal' => 44, 'Nombre' => 'Lamparas Recargables', 'Descripcion' => 'Lamparas', 'activo' => true, 'ID_UnidadOperativa' => 7],
            ['ID_GrupoPresupuestal' => 79, 'Nombre' => 'Viaticos', 'Descripcion' => 'Viaticos', 'activo' => true, 'ID_UnidadOperativa' => 8],
            ['ID_GrupoPresupuestal' => 81, 'Nombre' => 'Convivios y eventos Vtas', 'Descripcion' => 'Convivios y eventos Vtas', 'activo' => true, 'ID_UnidadOperativa' => 8],
            ['ID_GrupoPresupuestal' => 83, 'Nombre' => 'obsequios', 'Descripcion' => 'obsequios', 'activo' => true, 'ID_UnidadOperativa' => 8],
            ['ID_GrupoPresupuestal' => 85, 'Nombre' => 'Combustible', 'Descripcion' => 'Combustible', 'activo' => true, 'ID_UnidadOperativa' => 8],
            ['ID_GrupoPresupuestal' => 87, 'Nombre' => 'CRM y aplicaciones', 'Descripcion' => 'CRM y aplicaciones', 'activo' => true, 'ID_UnidadOperativa' => 8],
            ['ID_GrupoPresupuestal' => 89, 'Nombre' => 'Souvenir', 'Descripcion' => 'Souvenir', 'activo' => true, 'ID_UnidadOperativa' => 8],
            ['ID_GrupoPresupuestal' => 91, 'Nombre' => 'Retiro Cesantia y vejez', 'Descripcion' => 'Retiro Cesantia y vejez', 'activo' => true, 'ID_UnidadOperativa' => 8],
            ['ID_GrupoPresupuestal' => 93, 'Nombre' => 'Creditos infonavit', 'Descripcion' => 'Creditos infonavit', 'activo' => true, 'ID_UnidadOperativa' => 8],
            ['ID_GrupoPresupuestal' => 95, 'Nombre' => 'CFE', 'Descripcion' => 'CFE', 'activo' => true, 'ID_UnidadOperativa' => 8],
            ['ID_GrupoPresupuestal' => 97, 'Nombre' => 'Agua empleados', 'Descripcion' => 'agua', 'activo' => true, 'ID_UnidadOperativa' => 8],
            ['ID_GrupoPresupuestal' => 99, 'Nombre' => 'Software campus icarus y contpaq', 'Descripcion' => 'Software campus icarus y contpaq', 'activo' => true, 'ID_UnidadOperativa' => 8],
            ['ID_GrupoPresupuestal' => 101, 'Nombre' => 'Uniformes', 'Descripcion' => 'uniformes', 'activo' => true, 'ID_UnidadOperativa' => 8],
            ['ID_GrupoPresupuestal' => 103, 'Nombre' => 'Asesoramiento Cumplimiento PLD', 'Descripcion' => 'Asesoramiento PLD', 'activo' => true, 'ID_UnidadOperativa' => 8],
            ['ID_GrupoPresupuestal' => 105, 'Nombre' => 'Paneles solares', 'Descripcion' => 'Paneles solares', 'activo' => true, 'ID_UnidadOperativa' => 8],
            ['ID_GrupoPresupuestal' => 107, 'Nombre' => 'seguro propiedad', 'Descripcion' => 'seguro propiedad', 'activo' => true, 'ID_UnidadOperativa' => 8],
            ['ID_GrupoPresupuestal' => 109, 'Nombre' => 'Gastos sistemas', 'Descripcion' => 'gastos', 'activo' => true, 'ID_UnidadOperativa' => null],
            ['ID_GrupoPresupuestal' => 111, 'Nombre' => 'Consumibles de operacion', 'Descripcion' => 'Consumibles de operacion', 'activo' => true, 'ID_UnidadOperativa' => 13],
            ['ID_GrupoPresupuestal' => 112, 'Nombre' => 'Consumibles administrativos', 'Descripcion' => 'Consumibles administrativos', 'activo' => true, 'ID_UnidadOperativa' => 13],
            ['ID_GrupoPresupuestal' => 113, 'Nombre' => 'Mantenimiento de computo', 'Descripcion' => 'Mantto computo', 'activo' => true, 'ID_UnidadOperativa' => 13],
            ['ID_GrupoPresupuestal' => 114, 'Nombre' => 'Licencias de software', 'Descripcion' => 'licencias de software', 'activo' => true, 'ID_UnidadOperativa' => 13],
            ['ID_GrupoPresupuestal' => 115, 'Nombre' => 'Servicios de asesoria legal', 'Descripcion' => 'Asesoria legal', 'activo' => true, 'ID_UnidadOperativa' => 13],
            ['ID_GrupoPresupuestal' => 116, 'Nombre' => 'Servicios de auditoria externa', 'Descripcion' => 'Auditoria externa', 'activo' => true, 'ID_UnidadOperativa' => 13],
            ['ID_GrupoPresupuestal' => 117, 'Nombre' => 'Servicios de asesoria contable', 'Descripcion' => 'Asesoria contable', 'activo' => true, 'ID_UnidadOperativa' => 13],
            ['ID_GrupoPresupuestal' => 118, 'Nombre' => 'Gastos de representacion', 'Descripcion' => 'Representacion', 'activo' => true, 'ID_UnidadOperativa' => 13],
            ['ID_GrupoPresupuestal' => 119, 'Nombre' => 'Seguro de gastos medicos mayores', 'Descripcion' => 'Seguro gastos medicos', 'activo' => true, 'ID_UnidadOperativa' => 13],
            ['ID_GrupoPresupuestal' => 120, 'Nombre' => 'Fondo de ahorro', 'Descripcion' => 'Fondo de ahorro', 'activo' => true, 'ID_UnidadOperativa' => 13],
            ['ID_GrupoPresupuestal' => 121, 'Nombre' => 'Vales de despensa', 'Descripcion' => 'Vales despensa', 'activo' => true, 'ID_UnidadOperativa' => 13],
            ['ID_GrupoPresupuestal' => 122, 'Nombre' => 'Prima de seguro de vida', 'Descripcion' => 'Seguro de vida', 'activo' => true, 'ID_UnidadOperativa' => 13],
            ['ID_GrupoPresupuestal' => 123, 'Nombre' => 'Isr sobre nomina', 'Descripcion' => 'ISR nomina', 'activo' => true, 'ID_UnidadOperativa' => 13],
            ['ID_GrupoPresupuestal' => 124, 'Nombre' => 'Impuesto sobre nomina estatal', 'Descripcion' => 'ISN', 'activo' => true, 'ID_UnidadOperativa' => 13],
            ['ID_GrupoPresupuestal' => 125, 'Nombre' => 'Credito infonavit', 'Descripcion' => 'credito infonavit', 'activo' => true, 'ID_UnidadOperativa' => 13],
            ['ID_GrupoPresupuestal' => 126, 'Nombre' => 'Infonavit', 'Descripcion' => 'Infonavit', 'activo' => true, 'ID_UnidadOperativa' => 13],
            ['ID_GrupoPresupuestal' => 127, 'Nombre' => 'RCV', 'Descripcion' => 'RCV', 'activo' => true, 'ID_UnidadOperativa' => 13],
            ['ID_GrupoPresupuestal' => 128, 'Nombre' => 'IMSS', 'Descripcion' => 'IMSS', 'activo' => true, 'ID_UnidadOperativa' => 13],
            ['ID_GrupoPresupuestal' => 129, 'Nombre' => 'Saldos y salarios USA', 'Descripcion' => 'Salarios USA', 'activo' => true, 'ID_UnidadOperativa' => 13],
            ['ID_GrupoPresupuestal' => 130, 'Nombre' => 'Sueldos y salasarios', 'Descripcion' => 'sueldos', 'activo' => true, 'ID_UnidadOperativa' => 13],
            ['ID_GrupoPresupuestal' => 131, 'Nombre' => 'Renta equipo de City 32', 'Descripcion' => 'E', 'activo' => true, 'ID_UnidadOperativa' => 13],
            ['ID_GrupoPresupuestal' => 132, 'Nombre' => 'Publicidad aeropuerto', 'Descripcion' => 'publicidad', 'activo' => true, 'ID_UnidadOperativa' => 13],
            ['ID_GrupoPresupuestal' => 133, 'Nombre' => 'Gastos de plotter', 'Descripcion' => 'Gastos de plotter', 'activo' => true, 'ID_UnidadOperativa' => 13],
            ['ID_GrupoPresupuestal' => 134, 'Nombre' => 'Papeleria', 'Descripcion' => 'Papeleria', 'activo' => true, 'ID_UnidadOperativa' => 13],
            ['ID_GrupoPresupuestal' => 135, 'Nombre' => 'Capacitaciones fiscales', 'Descripcion' => 'Capacitaciones fiscales', 'activo' => true, 'ID_UnidadOperativa' => 13],
            ['ID_GrupoPresupuestal' => 136, 'Nombre' => 'Capacitaciones de construccion', 'Descripcion' => 'Capacitaciones', 'activo' => true, 'ID_UnidadOperativa' => 13],
            ['ID_GrupoPresupuestal' => 137, 'Nombre' => 'Intereses Jubi jubi', 'Descripcion' => 'interes', 'activo' => true, 'ID_UnidadOperativa' => 1],
            ['ID_GrupoPresupuestal' => 138, 'Nombre' => 'Seguro Equipo de transporte', 'Descripcion' => 'Seguros', 'activo' => true, 'ID_UnidadOperativa' => 9],
            ['ID_GrupoPresupuestal' => 139, 'Nombre' => 'Mantto Equipo de transporte', 'Descripcion' => 'Mantenimiento', 'activo' => true, 'ID_UnidadOperativa' => 9],
            ['ID_GrupoPresupuestal' => 140, 'Nombre' => 'Combustible equipo de transporte Avion', 'Descripcion' => 'combustible transporte avion', 'activo' => true, 'ID_UnidadOperativa' => 9],
            ['ID_GrupoPresupuestal' => 141, 'Nombre' => 'Combustible equipo de transporte', 'Descripcion' => 'combustible transporte city32', 'activo' => true, 'ID_UnidadOperativa' => 9],
            ['ID_GrupoPresupuestal' => 142, 'Nombre' => 'Mobiliario y equipo', 'Descripcion' => 'mobiliario', 'activo' => true, 'ID_UnidadOperativa' => 10],
            ['ID_GrupoPresupuestal' => 143, 'Nombre' => 'Equipo de computo', 'Descripcion' => 'equipo', 'activo' => true, 'ID_UnidadOperativa' => 10],
            ['ID_GrupoPresupuestal' => 144, 'Nombre' => 'Servicios oficina city32 MBSP INVESTMENTS L13', 'Descripcion' => 'Servicios oficina city32 MBSP INVESTMENTS L13', 'activo' => true, 'ID_UnidadOperativa' => 11],
            ['ID_GrupoPresupuestal' => 145, 'Nombre' => 'Cuota Mantto oficina city32 MBSP INVESTMENTS L13', 'Descripcion' => 'Cuota Mantto oficina city32 MBSP INVESTMENTS L13', 'activo' => true, 'ID_UnidadOperativa' => 11],
            ['ID_GrupoPresupuestal' => 146, 'Nombre' => 'Renta de oficina city31 MBSP INVESTMENTS L13', 'Descripcion' => 'Oficita L13 investments', 'activo' => true, 'ID_UnidadOperativa' => 11],
            ['ID_GrupoPresupuestal' => 147, 'Nombre' => 'Suscripcion de navegacion', 'Descripcion' => 'Suscripcion de navegación', 'activo' => true, 'ID_UnidadOperativa' => 12],
            ['ID_GrupoPresupuestal' => 148, 'Nombre' => 'Entrenamiento pilotos', 'Descripcion' => 'capacitacion', 'activo' => true, 'ID_UnidadOperativa' => 12],
            ['ID_GrupoPresupuestal' => 149, 'Nombre' => 'Mantenimiento del avion anual', 'Descripcion' => 'mantenimiento avion', 'activo' => true, 'ID_UnidadOperativa' => 12],
            ['ID_GrupoPresupuestal' => 150, 'Nombre' => 'Seguro avion', 'Descripcion' => 'Seguro avion', 'activo' => true, 'ID_UnidadOperativa' => 12],
            ['ID_GrupoPresupuestal' => 151, 'Nombre' => 'Renta Hangar', 'Descripcion' => 'Hangar avion', 'activo' => true, 'ID_UnidadOperativa' => 12],
            ['ID_GrupoPresupuestal' => 152, 'Nombre' => 'Administracion', 'Descripcion' => 'Administracion avion', 'activo' => true, 'ID_UnidadOperativa' => 12],
            ['ID_GrupoPresupuestal' => 153, 'Nombre' => 'Fee de empresa de administracion', 'Descripcion' => 'Fee de empresa de administracion', 'activo' => true, 'ID_UnidadOperativa' => 18],
            ['ID_GrupoPresupuestal' => 154, 'Nombre' => 'Fee de empresa de administracion', 'Descripcion' => 'Fee de empresa de administracion', 'activo' => true, 'ID_UnidadOperativa' => 20],
            ['ID_GrupoPresupuestal' => 155, 'Nombre' => 'Fee de empresa de administracion', 'Descripcion' => 'Fee de empresa de administracion', 'activo' => true, 'ID_UnidadOperativa' => 26],
            ['ID_GrupoPresupuestal' => 156, 'Nombre' => 'Fee de empresa de administracion', 'Descripcion' => 'Fee de empresa de administracion', 'activo' => true, 'ID_UnidadOperativa' => 32],
            ['ID_GrupoPresupuestal' => 157, 'Nombre' => 'Fee de empresa de administracion', 'Descripcion' => 'Fee de empresa de administracion', 'activo' => true, 'ID_UnidadOperativa' => 38],
            ['ID_GrupoPresupuestal' => 158, 'Nombre' => 'Insumos de papeleria y administracion (gasolina)', 'Descripcion' => 'Insumos de papeleria y administracion (gasolina)', 'activo' => true, 'ID_UnidadOperativa' => 38],
            ['ID_GrupoPresupuestal' => 159, 'Nombre' => 'Insumos de papeleria y administracion (gasolina)', 'Descripcion' => 'Insumos de papeleria y administracion (gasolina)', 'activo' => true, 'ID_UnidadOperativa' => 32],
            ['ID_GrupoPresupuestal' => 160, 'Nombre' => 'Insumos de papeleria y administracion (gasolina)', 'Descripcion' => 'Insumos de papeleria y administracion (gasolina)', 'activo' => true, 'ID_UnidadOperativa' => 26],
            ['ID_GrupoPresupuestal' => 161, 'Nombre' => 'Insumos de papeleria y administracion (gasolina)', 'Descripcion' => 'Insumos de papeleria y administracion (gasolina)', 'activo' => true, 'ID_UnidadOperativa' => 20],
            ['ID_GrupoPresupuestal' => 162, 'Nombre' => 'Insumos de papeleria y administracion (gasolina)', 'Descripcion' => 'Insumos de papeleria y administracion (gasolina)', 'activo' => true, 'ID_UnidadOperativa' => 18],
            ['ID_GrupoPresupuestal' => 163, 'Nombre' => 'Software de administracion', 'Descripcion' => 'Software de administracion', 'activo' => true, 'ID_UnidadOperativa' => 32],
            ['ID_GrupoPresupuestal' => 164, 'Nombre' => 'Software de administracion', 'Descripcion' => 'Software de administracion', 'activo' => true, 'ID_UnidadOperativa' => 38],
            ['ID_GrupoPresupuestal' => 165, 'Nombre' => 'Software de administracion', 'Descripcion' => 'Software de administracion', 'activo' => true, 'ID_UnidadOperativa' => 26],
            ['ID_GrupoPresupuestal' => 166, 'Nombre' => 'Software de administracion', 'Descripcion' => 'Software de administracion', 'activo' => true, 'ID_UnidadOperativa' => 20],
            ['ID_GrupoPresupuestal' => 167, 'Nombre' => 'Software de administracion', 'Descripcion' => 'Software de administracion', 'activo' => true, 'ID_UnidadOperativa' => 18],
            ['ID_GrupoPresupuestal' => 168, 'Nombre' => 'Comisiones bancarias', 'Descripcion' => 'Comisiones bancarias', 'activo' => true, 'ID_UnidadOperativa' => 18],
            ['ID_GrupoPresupuestal' => 169, 'Nombre' => 'Gastos legales y de cobranza', 'Descripcion' => 'Gastos legales y de cobranza', 'activo' => true, 'ID_UnidadOperativa' => 26],
            ['ID_GrupoPresupuestal' => 170, 'Nombre' => 'Gastos legales y de cobranza', 'Descripcion' => 'Gastos legales y de cobranza', 'activo' => true, 'ID_UnidadOperativa' => 38],
            ['ID_GrupoPresupuestal' => 171, 'Nombre' => 'Gastos legales y de cobranza', 'Descripcion' => 'Gastos legales y de cobranza', 'activo' => true, 'ID_UnidadOperativa' => 32],
            ['ID_GrupoPresupuestal' => 172, 'Nombre' => 'Gastos legales y de cobranza', 'Descripcion' => 'Gastos legales y de cobranza', 'activo' => true, 'ID_UnidadOperativa' => 18],
            ['ID_GrupoPresupuestal' => 173, 'Nombre' => 'Gastos legales y de cobranza', 'Descripcion' => 'Gastos legales y de cobranza', 'activo' => true, 'ID_UnidadOperativa' => 20],
            ['ID_GrupoPresupuestal' => 174, 'Nombre' => 'Asambleas ordinarias y extraordinarias', 'Descripcion' => 'Asambleas ordinarias y extraordinarias', 'activo' => true, 'ID_UnidadOperativa' => 26],
            ['ID_GrupoPresupuestal' => 175, 'Nombre' => 'Asambleas ordinarias y extraordinarias', 'Descripcion' => 'Asambleas ordinarias y extraordinarias', 'activo' => true, 'ID_UnidadOperativa' => 38],
            ['ID_GrupoPresupuestal' => 176, 'Nombre' => 'Asambleas ordinarias y extraordinarias', 'Descripcion' => 'Asambleas ordinarias y extraordinarias', 'activo' => true, 'ID_UnidadOperativa' => 32],
            ['ID_GrupoPresupuestal' => 177, 'Nombre' => 'Asambleas ordinarias y extraordinarias', 'Descripcion' => 'Asambleas ordinarias y extraordinarias', 'activo' => true, 'ID_UnidadOperativa' => 18],
            ['ID_GrupoPresupuestal' => 178, 'Nombre' => 'Asambleas ordinarias y extraordinarias', 'Descripcion' => 'Asambleas ordinarias y extraordinarias', 'activo' => true, 'ID_UnidadOperativa' => 20],
            ['ID_GrupoPresupuestal' => 179, 'Nombre' => 'Comisiones bancarias', 'Descripcion' => 'Comisiones bancarias', 'activo' => true, 'ID_UnidadOperativa' => 38],
            ['ID_GrupoPresupuestal' => 180, 'Nombre' => 'Comisiones bancarias', 'Descripcion' => 'Comisiones bancarias', 'activo' => true, 'ID_UnidadOperativa' => 32],
            ['ID_GrupoPresupuestal' => 181, 'Nombre' => 'Comisiones bancarias', 'Descripcion' => 'Comisiones bancarias', 'activo' => true, 'ID_UnidadOperativa' => 26],
            ['ID_GrupoPresupuestal' => 182, 'Nombre' => 'Comisiones bancarias', 'Descripcion' => 'Comisiones bancarias', 'activo' => true, 'ID_UnidadOperativa' => 20],
            ['ID_GrupoPresupuestal' => 183, 'Nombre' => 'Energia electrica', 'Descripcion' => 'Energia electrica', 'activo' => true, 'ID_UnidadOperativa' => 21],
            ['ID_GrupoPresupuestal' => 184, 'Nombre' => 'Energia electrica', 'Descripcion' => 'Energia electrica', 'activo' => true, 'ID_UnidadOperativa' => 33],
            ['ID_GrupoPresupuestal' => 185, 'Nombre' => 'Energia electrica', 'Descripcion' => 'Energia electrica', 'activo' => true, 'ID_UnidadOperativa' => 27],
            ['ID_GrupoPresupuestal' => 186, 'Nombre' => 'Energia electrica', 'Descripcion' => 'Energia electrica', 'activo' => true, 'ID_UnidadOperativa' => 17],
            ['ID_GrupoPresupuestal' => 187, 'Nombre' => 'Energia electrica', 'Descripcion' => 'Energia electrica', 'activo' => true, 'ID_UnidadOperativa' => 43],
            ['ID_GrupoPresupuestal' => 188, 'Nombre' => 'Servicio de recoleccion de basura (32u)', 'Descripcion' => 'Servicio de recoleccion de basura (32u)', 'activo' => true, 'ID_UnidadOperativa' => 33],
            ['ID_GrupoPresupuestal' => 189, 'Nombre' => 'Servicio de recoleccion de basura', 'Descripcion' => 'Servicio de recoleccion de basura', 'activo' => true, 'ID_UnidadOperativa' => 27],
            ['ID_GrupoPresupuestal' => 190, 'Nombre' => 'Servicio de recoleccion de basura', 'Descripcion' => 'Servicio de recoleccion de basura', 'activo' => true, 'ID_UnidadOperativa' => 17],
            ['ID_GrupoPresupuestal' => 191, 'Nombre' => 'Servicio de recoleccion de basura', 'Descripcion' => 'Servicio de recoleccion de basura', 'activo' => true, 'ID_UnidadOperativa' => 43],
            ['ID_GrupoPresupuestal' => 192, 'Nombre' => 'Servicio de recoleccion de basura', 'Descripcion' => 'Servicio de recoleccion de basura', 'activo' => true, 'ID_UnidadOperativa' => 21],
            ['ID_GrupoPresupuestal' => 194, 'Nombre' => 'Póliza de seguro', 'Descripcion' => 'Póliza de seguro', 'activo' => true, 'ID_UnidadOperativa' => 34],
            ['ID_GrupoPresupuestal' => 195, 'Nombre' => 'Póliza de seguro', 'Descripcion' => 'Póliza de seguro', 'activo' => true, 'ID_UnidadOperativa' => 40],
            ['ID_GrupoPresupuestal' => 196, 'Nombre' => 'Póliza de seguro', 'Descripcion' => 'Póliza de seguro', 'activo' => true, 'ID_UnidadOperativa' => 28],
            ['ID_GrupoPresupuestal' => 197, 'Nombre' => 'Póliza de seguro', 'Descripcion' => 'Póliza de seguro', 'activo' => true, 'ID_UnidadOperativa' => 22],
            ['ID_GrupoPresupuestal' => 198, 'Nombre' => 'Mtto Extintores', 'Descripcion' => 'Mtto Extintores', 'activo' => true, 'ID_UnidadOperativa' => 22],
            ['ID_GrupoPresupuestal' => 199, 'Nombre' => 'Mtto Extintores', 'Descripcion' => 'Mtto Extintores', 'activo' => true, 'ID_UnidadOperativa' => 28],
            ['ID_GrupoPresupuestal' => 200, 'Nombre' => 'Mtto Extintores', 'Descripcion' => 'Mtto Extintores', 'activo' => true, 'ID_UnidadOperativa' => 40],
            ['ID_GrupoPresupuestal' => 201, 'Nombre' => 'Mtto Extintores', 'Descripcion' => 'Mtto Extintores', 'activo' => true, 'ID_UnidadOperativa' => 34],
            ['ID_GrupoPresupuestal' => 202, 'Nombre' => 'Mtto Extintores (2)', 'Descripcion' => 'Mtto Extintores', 'activo' => true, 'ID_UnidadOperativa' => 16],
            ['ID_GrupoPresupuestal' => 203, 'Nombre' => 'Seguridad / personal de vigilancia ', 'Descripcion' => 'Seguridad / personal de vigilancia ', 'activo' => true, 'ID_UnidadOperativa' => 15],
            ['ID_GrupoPresupuestal' => 204, 'Nombre' => 'Seguridad / personal de vigilancia ', 'Descripcion' => 'Seguridad / personal de vigilancia ', 'activo' => true, 'ID_UnidadOperativa' => 35],
            ['ID_GrupoPresupuestal' => 205, 'Nombre' => 'Seguridad / personal de vigilancia ', 'Descripcion' => 'Seguridad / personal de vigilancia ', 'activo' => true, 'ID_UnidadOperativa' => 29],
            ['ID_GrupoPresupuestal' => 206, 'Nombre' => 'Seguridad / personal de vigilancia ', 'Descripcion' => 'Seguridad / personal de vigilancia ', 'activo' => true, 'ID_UnidadOperativa' => 39],
            ['ID_GrupoPresupuestal' => 207, 'Nombre' => 'Seguridad / personal de vigilancia ', 'Descripcion' => 'Seguridad / personal de vigilancia ', 'activo' => true, 'ID_UnidadOperativa' => 23],
            ['ID_GrupoPresupuestal' => 208, 'Nombre' => 'Mantenimiento pluma / rejas acceso', 'Descripcion' => 'Mantenimiento pluma / rejas acceso', 'activo' => true, 'ID_UnidadOperativa' => 40],
            ['ID_GrupoPresupuestal' => 209, 'Nombre' => 'Mantenimiento pluma, interfon y tags', 'Descripcion' => 'Mantenimiento pluma, interfon y tags', 'activo' => true, 'ID_UnidadOperativa' => 34],
            ['ID_GrupoPresupuestal' => 210, 'Nombre' => 'Mantenimiento pluma (1)', 'Descripcion' => 'Mantenimiento pluma (1)', 'activo' => true, 'ID_UnidadOperativa' => 16],
            ['ID_GrupoPresupuestal' => 211, 'Nombre' => 'Mantenimiento pluma (1)', 'Descripcion' => 'Mantenimiento pluma (1)', 'activo' => true, 'ID_UnidadOperativa' => 28],
            ['ID_GrupoPresupuestal' => 212, 'Nombre' => 'Mantenimiento pluma (1)', 'Descripcion' => 'Mantenimiento pluma (1)', 'activo' => true, 'ID_UnidadOperativa' => 22],
            ['ID_GrupoPresupuestal' => 213, 'Nombre' => 'servicio de mantenimiento, jardineria, limpieza, piscina', 'Descripcion' => 'servicio de mantenimiento, jardineria, limpieza, piscina', 'activo' => true, 'ID_UnidadOperativa' => 15],
            ['ID_GrupoPresupuestal' => 214, 'Nombre' => 'servicio de mantenimiento, jardineria, limpieza, piscina', 'Descripcion' => 'servicio de mantenimiento, jardineria, limpieza, piscina', 'activo' => true, 'ID_UnidadOperativa' => 35],
            ['ID_GrupoPresupuestal' => 215, 'Nombre' => 'servicio de mantenimiento, jardineria, limpieza, piscina', 'Descripcion' => 'servicio de mantenimiento, jardineria, limpieza, piscina', 'activo' => true, 'ID_UnidadOperativa' => 29],
            ['ID_GrupoPresupuestal' => 216, 'Nombre' => 'servicio de mantenimiento, jardineria, limpieza, piscina', 'Descripcion' => 'servicio de mantenimiento, jardineria, limpieza, piscina', 'activo' => true, 'ID_UnidadOperativa' => 39],
            ['ID_GrupoPresupuestal' => 217, 'Nombre' => 'servicio de mantenimiento, jardineria, limpieza, piscina', 'Descripcion' => 'servicio de mantenimiento, jardineria, limpieza, piscina', 'activo' => true, 'ID_UnidadOperativa' => 23],
            ['ID_GrupoPresupuestal' => 218, 'Nombre' => 'Insumos / Servicio de fumigación áreas comunes', 'Descripcion' => 'Insumos / Servicio de fumigación áreas comunes', 'activo' => true, 'ID_UnidadOperativa' => 30],
            ['ID_GrupoPresupuestal' => 219, 'Nombre' => 'Insumos / Servicio de fumigación áreas comunes', 'Descripcion' => 'Insumos / Servicio de fumigación áreas comunes', 'activo' => true, 'ID_UnidadOperativa' => 41],
            ['ID_GrupoPresupuestal' => 220, 'Nombre' => 'Insumos / Servicio de fumigación áreas comunes', 'Descripcion' => 'Insumos / Servicio de fumigación áreas comunes', 'activo' => true, 'ID_UnidadOperativa' => 19],
            ['ID_GrupoPresupuestal' => 221, 'Nombre' => 'Insumos / Servicio de fumigación áreas comunes', 'Descripcion' => 'Insumos / Servicio de fumigación áreas comunes', 'activo' => true, 'ID_UnidadOperativa' => 36],
            ['ID_GrupoPresupuestal' => 222, 'Nombre' => 'Insumos / Servicio de fumigación áreas comunes', 'Descripcion' => 'Insumos / Servicio de fumigación áreas comunes', 'activo' => true, 'ID_UnidadOperativa' => 24],
            ['ID_GrupoPresupuestal' => 223, 'Nombre' => 'Insumos y materiales de Jardineria ', 'Descripcion' => 'Insumos y materiales de Jardineria ', 'activo' => true, 'ID_UnidadOperativa' => 30],
            ['ID_GrupoPresupuestal' => 224, 'Nombre' => 'Insumos y materiales de Jardineria ', 'Descripcion' => 'Insumos y materiales de Jardineria ', 'activo' => true, 'ID_UnidadOperativa' => 41],
            ['ID_GrupoPresupuestal' => 225, 'Nombre' => 'Insumos y materiales de Jardineria ', 'Descripcion' => 'Insumos y materiales de Jardineria ', 'activo' => true, 'ID_UnidadOperativa' => 19],
            ['ID_GrupoPresupuestal' => 226, 'Nombre' => 'Insumos y materiales de Jardineria ', 'Descripcion' => 'Insumos y materiales de Jardineria ', 'activo' => true, 'ID_UnidadOperativa' => 36],
            ['ID_GrupoPresupuestal' => 227, 'Nombre' => 'Insumos y materiales de Jardineria ', 'Descripcion' => 'Insumos y materiales de Jardineria ', 'activo' => true, 'ID_UnidadOperativa' => 24],
            ['ID_GrupoPresupuestal' => 233, 'Nombre' => 'Insumos y materiales de iluminación', 'Descripcion' => 'Insumos y materiales de iluminación', 'activo' => true, 'ID_UnidadOperativa' => 30],
            ['ID_GrupoPresupuestal' => 234, 'Nombre' => 'Insumos y materiales de iluminación', 'Descripcion' => 'Insumos y materiales de iluminación', 'activo' => true, 'ID_UnidadOperativa' => 41],
            ['ID_GrupoPresupuestal' => 235, 'Nombre' => 'Insumos y materiales de iluminación', 'Descripcion' => 'Insumos y materiales de iluminación', 'activo' => true, 'ID_UnidadOperativa' => 36],
            ['ID_GrupoPresupuestal' => 236, 'Nombre' => 'Insumos y materiales de iluminación', 'Descripcion' => 'Insumos y materiales de iluminación', 'activo' => true, 'ID_UnidadOperativa' => 24],
            ['ID_GrupoPresupuestal' => 237, 'Nombre' => 'Insumos y materiales de iluminación', 'Descripcion' => 'Insumos y materiales de iluminación', 'activo' => true, 'ID_UnidadOperativa' => 19],
            ['ID_GrupoPresupuestal' => 238, 'Nombre' => 'Insumos y materiales de limpieza de áreas comunes', 'Descripcion' => 'Insumos y materiales de limpieza de áreas comunes', 'activo' => true, 'ID_UnidadOperativa' => 30],
            ['ID_GrupoPresupuestal' => 239, 'Nombre' => 'Insumos y materiales de limpieza de áreas comunes', 'Descripcion' => 'Insumos y materiales de limpieza de áreas comunes', 'activo' => true, 'ID_UnidadOperativa' => 41],
            ['ID_GrupoPresupuestal' => 240, 'Nombre' => 'Insumos y materiales de limpieza de áreas comunes', 'Descripcion' => 'Insumos y materiales de limpieza de áreas comunes', 'activo' => true, 'ID_UnidadOperativa' => 19],
            ['ID_GrupoPresupuestal' => 241, 'Nombre' => 'Insumos y materiales de limpieza de áreas comunes', 'Descripcion' => 'Insumos y materiales de limpieza de áreas comunes', 'activo' => true, 'ID_UnidadOperativa' => 36],
            ['ID_GrupoPresupuestal' => 242, 'Nombre' => 'Insumos y materiales de limpieza de áreas comunes', 'Descripcion' => 'Insumos y materiales de limpieza de áreas comunes', 'activo' => true, 'ID_UnidadOperativa' => 24],
            ['ID_GrupoPresupuestal' => 243, 'Nombre' => 'Insumos y materiales de pintura áreas comunes', 'Descripcion' => 'Insumos y materiales de pintura áreas comunes', 'activo' => true, 'ID_UnidadOperativa' => 30],
            ['ID_GrupoPresupuestal' => 244, 'Nombre' => 'Insumos y materiales de pintura áreas comunes', 'Descripcion' => 'Insumos y materiales de pintura áreas comunes', 'activo' => true, 'ID_UnidadOperativa' => 41],
            ['ID_GrupoPresupuestal' => 245, 'Nombre' => 'Insumos y materiales de pintura áreas comunes', 'Descripcion' => 'Insumos y materiales de pintura áreas comunes', 'activo' => true, 'ID_UnidadOperativa' => 19],
            ['ID_GrupoPresupuestal' => 246, 'Nombre' => 'Insumos y materiales de pintura áreas comunes', 'Descripcion' => 'Insumos y materiales de pintura áreas comunes', 'activo' => true, 'ID_UnidadOperativa' => 36],
            ['ID_GrupoPresupuestal' => 247, 'Nombre' => 'Insumos y materiales de pintura áreas comunes', 'Descripcion' => 'Insumos y materiales de pintura áreas comunes', 'activo' => true, 'ID_UnidadOperativa' => 24],
            ['ID_GrupoPresupuestal' => 248, 'Nombre' => 'Insumos y materiales de impermeabilizante áreas comunes', 'Descripcion' => 'Insumos y materiales de impermeabilizante áreas comunes', 'activo' => true, 'ID_UnidadOperativa' => 30],
            ['ID_GrupoPresupuestal' => 249, 'Nombre' => 'Insumos y materiales de impermeabilizante áreas comunes', 'Descripcion' => 'Insumos y materiales de impermeabilizante áreas comunes', 'activo' => true, 'ID_UnidadOperativa' => 41],
            ['ID_GrupoPresupuestal' => 250, 'Nombre' => 'Insumos y materiales de impermeabilizante áreas comunes', 'Descripcion' => 'Insumos y materiales de impermeabilizante áreas comunes', 'activo' => true, 'ID_UnidadOperativa' => 19],
            ['ID_GrupoPresupuestal' => 251, 'Nombre' => 'Insumos y materiales de impermeabilizante áreas comunes', 'Descripcion' => 'Insumos y materiales de impermeabilizante áreas comunes', 'activo' => true, 'ID_UnidadOperativa' => 36],
            ['ID_GrupoPresupuestal' => 252, 'Nombre' => 'Insumos y materiales de impermeabilizante áreas comunes', 'Descripcion' => 'Insumos y materiales de impermeabilizante áreas comunes', 'activo' => true, 'ID_UnidadOperativa' => 24],
            ['ID_GrupoPresupuestal' => 253, 'Nombre' => 'Insumos y materiales para mantenimiento electrico ', 'Descripcion' => 'Insumos y materiales para mantenimiento electrico ', 'activo' => true, 'ID_UnidadOperativa' => 30],
            ['ID_GrupoPresupuestal' => 254, 'Nombre' => 'Insumos y materiales para mantenimiento electrico ', 'Descripcion' => 'Insumos y materiales para mantenimiento electrico ', 'activo' => true, 'ID_UnidadOperativa' => 41],
            ['ID_GrupoPresupuestal' => 255, 'Nombre' => 'Insumos y materiales para mantenimiento electrico ', 'Descripcion' => 'Insumos y materiales para mantenimiento electrico ', 'activo' => true, 'ID_UnidadOperativa' => 19],
            ['ID_GrupoPresupuestal' => 256, 'Nombre' => 'Insumos y materiales para mantenimiento electrico ', 'Descripcion' => 'Insumos y materiales para mantenimiento electrico ', 'activo' => true, 'ID_UnidadOperativa' => 36],
            ['ID_GrupoPresupuestal' => 257, 'Nombre' => 'Insumos y materiales para mantenimiento electrico ', 'Descripcion' => 'Insumos y materiales para mantenimiento electrico ', 'activo' => true, 'ID_UnidadOperativa' => 24],
            ['ID_GrupoPresupuestal' => 258, 'Nombre' => 'Insumos y materiales para mantenimiento de mobiliario', 'Descripcion' => 'Insumos y materiales para mantenimiento de mobiliario', 'activo' => true, 'ID_UnidadOperativa' => 41],
            ['ID_GrupoPresupuestal' => 259, 'Nombre' => 'Insumos y materiales para mantenimiento hidraulico ', 'Descripcion' => 'Insumos y materiales para mantenimiento hidraulico ', 'activo' => true, 'ID_UnidadOperativa' => 30],
            ['ID_GrupoPresupuestal' => 260, 'Nombre' => 'Insumos y materiales para mantenimiento hidraulico ', 'Descripcion' => 'Insumos y materiales para mantenimiento hidraulico ', 'activo' => true, 'ID_UnidadOperativa' => 19],
            ['ID_GrupoPresupuestal' => 261, 'Nombre' => 'Insumos y materiales para mantenimiento hidraulico ', 'Descripcion' => 'Insumos y materiales para mantenimiento hidraulico ', 'activo' => true, 'ID_UnidadOperativa' => 36],
            ['ID_GrupoPresupuestal' => 262, 'Nombre' => 'Insumos y materiales para mantenimiento hidraulico ', 'Descripcion' => 'Insumos y materiales para mantenimiento hidraulico ', 'activo' => true, 'ID_UnidadOperativa' => 24],
            ['ID_GrupoPresupuestal' => 263, 'Nombre' => 'Materiales de mantenimiento', 'Descripcion' => 'Materiales de mantenimiento', 'activo' => true, 'ID_UnidadOperativa' => 25],
            ['ID_GrupoPresupuestal' => 264, 'Nombre' => 'Materiales de mantenimiento', 'Descripcion' => 'Materiales de mantenimiento', 'activo' => true, 'ID_UnidadOperativa' => 42],
            ['ID_GrupoPresupuestal' => 265, 'Nombre' => 'Materiales de mantenimiento', 'Descripcion' => 'Materiales de mantenimiento|', 'activo' => true, 'ID_UnidadOperativa' => 37],
            ['ID_GrupoPresupuestal' => 266, 'Nombre' => 'Materiales de mantenimiento', 'Descripcion' => 'Materiales de mantenimiento', 'activo' => true, 'ID_UnidadOperativa' => 31],
            ['ID_GrupoPresupuestal' => 267, 'Nombre' => 'Materiales de mantenimiento', 'Descripcion' => 'Materiales de mantenimiento', 'activo' => true, 'ID_UnidadOperativa' => 14],
            ['ID_GrupoPresupuestal' => 273, 'Nombre' => 'Otros gastos/Fondo de reserva', 'Descripcion' => 'Otros gastos/Fondo de reserva', 'activo' => true, 'ID_UnidadOperativa' => 42],
            ['ID_GrupoPresupuestal' => 274, 'Nombre' => 'Fondo de reserva', 'Descripcion' => 'Fondo de reserva', 'activo' => true, 'ID_UnidadOperativa' => 25],
            ['ID_GrupoPresupuestal' => 275, 'Nombre' => 'Fondo de reserva', 'Descripcion' => 'Fondo de reserva', 'activo' => true, 'ID_UnidadOperativa' => 37],
            ['ID_GrupoPresupuestal' => 276, 'Nombre' => 'Fondo de reserva', 'Descripcion' => 'Fondo de reserva', 'activo' => true, 'ID_UnidadOperativa' => 31],
            ['ID_GrupoPresupuestal' => 277, 'Nombre' => 'Fondo de reserva', 'Descripcion' => 'Fondo de reserva', 'activo' => true, 'ID_UnidadOperativa' => 14],
            ['ID_GrupoPresupuestal' => 278, 'Nombre' => 'Mantenimiento a biodigestores (4) cap. 5000m3 c/u', 'Descripcion' => 'Mantenimiento a biodigestores (4) cap. 5000m3 c/u', 'activo' => true, 'ID_UnidadOperativa' => 25],
            ['ID_GrupoPresupuestal' => 279, 'Nombre' => 'Mantenimiento a biodigestores (4) cap. 5000m3 c/u', 'Descripcion' => 'Mantenimiento a biodigestores (4) cap. 5000m3 c/u', 'activo' => true, 'ID_UnidadOperativa' => 42],
            ['ID_GrupoPresupuestal' => 280, 'Nombre' => 'Mantenimiento a biodigestores (4) cap. 5000m3 c/u', 'Descripcion' => 'Mantenimiento a biodigestores (4) cap. 5000m3 c/u', 'activo' => true, 'ID_UnidadOperativa' => 37],
            ['ID_GrupoPresupuestal' => 281, 'Nombre' => 'Mantenimiento a biodigestores (4) cap. 5000m3 c/u', 'Descripcion' => 'Mantenimiento a biodigestores (4) cap. 5000m3 c/u', 'activo' => true, 'ID_UnidadOperativa' => 31],
            ['ID_GrupoPresupuestal' => 282, 'Nombre' => 'Mantenimiento a biodigestores (4) cap. 5000m3 c/u', 'Descripcion' => 'Mantenimiento a biodigestores (4) cap. 5000m3 c/u', 'activo' => true, 'ID_UnidadOperativa' => 14],
            ['ID_GrupoPresupuestal' => 283, 'Nombre' => 'insumos de translados (gasolina)', 'Descripcion' => 'insumos de translados (gasolina)', 'activo' => true, 'ID_UnidadOperativa' => 30],
            ['ID_GrupoPresupuestal' => 284, 'Nombre' => 'insumos de translados (gasolina)', 'Descripcion' => 'insumos de translados (gasolina)', 'activo' => true, 'ID_UnidadOperativa' => 41],
            ['ID_GrupoPresupuestal' => 285, 'Nombre' => 'insumos de translados (gasolina)', 'Descripcion' => 'insumos de translados (gasolina)', 'activo' => true, 'ID_UnidadOperativa' => 19],
            ['ID_GrupoPresupuestal' => 286, 'Nombre' => 'insumos de translados (gasolina)', 'Descripcion' => 'insumos de translados (gasolina)', 'activo' => true, 'ID_UnidadOperativa' => 36],
            ['ID_GrupoPresupuestal' => 287, 'Nombre' => 'insumos de translados (gasolina)', 'Descripcion' => 'insumos de translados (gasolina)', 'activo' => true, 'ID_UnidadOperativa' => 24],
            ['ID_GrupoPresupuestal' => 288, 'Nombre' => 'insumos y materiales para piscina', 'Descripcion' => 'insumos y materiales para piscina', 'activo' => true, 'ID_UnidadOperativa' => 30],
            ['ID_GrupoPresupuestal' => 289, 'Nombre' => 'insumos y materiales para piscina', 'Descripcion' => 'insumos y materiales para piscina', 'activo' => true, 'ID_UnidadOperativa' => 41],
            ['ID_GrupoPresupuestal' => 290, 'Nombre' => 'insumos y materiales para piscina', 'Descripcion' => 'insumos y materiales para piscina', 'activo' => true, 'ID_UnidadOperativa' => 19],
            ['ID_GrupoPresupuestal' => 291, 'Nombre' => 'insumos y materiales para piscina', 'Descripcion' => 'insumos y materiales para piscina', 'activo' => true, 'ID_UnidadOperativa' => 36],
            ['ID_GrupoPresupuestal' => 292, 'Nombre' => 'insumos y materiales para piscina', 'Descripcion' => 'insumos y materiales para piscina', 'activo' => true, 'ID_UnidadOperativa' => 24],
            ['ID_GrupoPresupuestal' => 271, 'Nombre' => 'Mantenimiento de bombas (4 cisternas, 4 bombas sumergibles, 4 presurizadores, 1 bomba para piscina)', 'Descripcion' => 'Materiales de bombas (4 cisternas, 4 bombas sumergibles, 4 presurizadores, 1 bomba para piscina)', 'activo' => true, 'ID_UnidadOperativa' => 31],
            ['ID_GrupoPresupuestal' => 269, 'Nombre' => 'Mantenimiento de bombas (4 cisternas, 4 bombas sumergibles, 4 presurizadores, 1 bomba para piscina)', 'Descripcion' => 'Materiales de bombas (4 cisternas, 4 bombas sumergibles, 4 presurizadores, 1 bomba para piscina)', 'activo' => true, 'ID_UnidadOperativa' => 42],
            ['ID_GrupoPresupuestal' => 268, 'Nombre' => 'Mantenimiento de bombas (4 cisternas, 4 bombas sumergibles, 4 presurizadores, 1 bomba para piscina)', 'Descripcion' => 'Materiales de bombas (4 cisternas, 4 bombas sumergibles, 4 presurizadores, 1 bomba para piscina)', 'activo' => true, 'ID_UnidadOperativa' => 25],
            ['ID_GrupoPresupuestal' => 272, 'Nombre' => 'Mantenimiento de bombas (4 cisternas, 4 bombas sumergibles, 4 presurizadores, 1 bomba para piscina)', 'Descripcion' => 'Materiales de bombas (4 cisternas, 4 bombas sumergibles, 4 presurizadores, 1 bomba para piscina)', 'activo' => true, 'ID_UnidadOperativa' => 14],
            ['ID_GrupoPresupuestal' => 270, 'Nombre' => 'Mantenimiento de bombas (4 cisternas, 4 bombas sumergibles, 4 presurizadores, 1 bomba para piscina)', 'Descripcion' => 'Materiales de bombas (4 cisternas, 4 bombas sumergibles, 4 presurizadores, 1 bomba para piscina)', 'activo' => true, 'ID_UnidadOperativa' => 37],
        ];

        foreach ($data as $row) {
            $exists = $this->db->table('GrupoPresupuestal')
                ->where('ID_GrupoPresupuestal', $row['ID_GrupoPresupuestal'])
                ->countAllResults();

            if ($exists === 0) {
                $this->db->table('GrupoPresupuestal')->insert($row);
            } else {
                $this->db->table('GrupoPresupuestal')
                    ->where('ID_GrupoPresupuestal', $row['ID_GrupoPresupuestal'])
                    ->update($row);
            }
        }
    }

    public function down()
    {
        $this->db->table('GrupoPresupuestal')->where('ID_GrupoPresupuestal >', 0)->delete();
    }
}
